### PR TITLE
Holy build for sharing binary

### PR DESCRIPTION
**Pull request by k3yavi**
libseq is messing up the zlib

### CODE REVIEW

**Comment by k3yavi** [comment]
The pull request is compiling through drone and ready to merge.

**Comment by rob-p** [comment]
Let's not pull this into develop yet

**Comment by rob-p** [comment]
ohhh, this is pufferfish; sorry ;P

**Comment by k3yavi** [comment]
No worries, can you give me write access? I need to test couple of things and have to enable the switch on drone to work.

**Pull request merged**
